velero:
  configuration:
    backupStorageLocation:
    - name: bsl-aws-velero
      provider: aws
      bucket: 934382447941-eu-central-1-velero
      default: true
      config:
        region: eu-central-1

  serviceAccount:
    server:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::934382447941:role/velero

  schedules:
    hourly-backup:
      disabled: false
      schedule: "0 * * * *"
      template:
        ttl: "1h"
        storageLocation: bsl-aws-velero
        includedNamespaces:
          - "confluent"
