repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: mixed-line-ending
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true 
      - id: terraform_fmt
      - id: terraform_providers_lock
        args:
          - --args=-platform=linux_arm64
          - --args=-platform=linux_amd64
          - --args=-platform=darwin_amd64
          - --args=-platform=windows_amd64
          - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md     
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_tflint
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--skip-check CKV_AWS_356
          - --args=--skip-check CKV_AWS_111
          - --args=--skip-check CKV_TF_1
