##
## Configuration settings related to Velero installation namespace
##
velero:
  image:
    repository: repository.eu-central-1.aws.int.kn/velero/velero

  # Number of old history to retain to allow rollback (If not set, default Kubernetes value is set to 10)
  # revisionHistoryLimit: 1

  # Resource requests/limits to specify for the Velero deployment.
  # https://velero.io/docs/v1.6/customize-installation/#customize-resource-requests-and-limits
  resources:
    requests:
      cpu: 500m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi

  # Init containers to add to the Velero deployment's pod spec. At least one plugin provider image is required.
  # If the value is a string then it is evaluated as a template.
  initContainers:
  #  - name: velero-plugin-for-csi
  #    image: repository.eu-central-1.aws.int.kn/velero/velero-plugin-for-csi:v0.6.0
  #    imagePullPolicy: IfNotPresent
  #    volumeMounts:
  #      - mountPath: /target
  #        name: plugins
    - name: velero-plugin-for-aws
      image: repository.eu-central-1.aws.int.kn/velero/velero-plugin-for-aws:v1.8.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

  kubectl:
    image:
      repository: repository.eu-central-1.aws.int.kn/bitnami/kubectl
      # Digest value example: sha256:d238835e151cec91c6a811fe3a89a66d3231d9f64d09e5f3c49552672d271f38.
      # If used, it will take precedence over the kubectl.image.tag.
      # digest:
      # kubectl image tag. If used, it will take precedence over the cluster Kubernetes version.
      # tag: 1.16.15
    # Container Level Security Context for the 'kubectl' container of the crd jobs. Optional.
    # See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
    containerSecurityContext: {}
    # Resource requests/limits to specify for the upgrade/cleanup job. Optional
    resources: {}
    # Annotations to set for the upgrade/cleanup job. Optional.
    annotations: {}
    # Labels to set for the upgrade/cleanup job. Optional.
    labels: {}



  ##
  ## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
  ## and additional server settings.
  ##
  configuration:
    # Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
    # See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
    backupStorageLocation:
      # name is the name of the backup storage location where backups should be stored. If a name is not provided,
      # a backup storage location will be created with the name "default". Optional.
    - name: bsl-aws-velero
      # provider is the name for the backup storage location provider.
      provider: aws
      # bucket is the name of the bucket to store backups in. Required.
      bucket: 934382447941-eu-central-1-velero
      # caCert defines a base64 encoded CA bundle to use when verifying TLS connections to the provider. Optional.
      caCert:
      # prefix is the directory under which all Velero data should be stored within the bucket. Optional.
      prefix:
      # default indicates this location is the default backup storage location. Optional.
      default: true
      # validationFrequency defines how frequently Velero should validate the object storage. Optional.
      validationFrequency:
      # accessMode determines if velero can write to this backup storage location. Optional.
      # default to ReadWrite, ReadOnly is used during migrations and restores.
      accessMode: ReadWrite
      credential:
        # name of the secret used by this backupStorageLocation.
        name:
        # name of key that contains the secret data to be used.
        key:
      # Additional provider-specific configuration. See link above
      # for details of required/optional fields for your provider.
      config:
        region: eu-central-1
      #  s3ForcePathStyle:
      #  s3Url:
      #  kmsKeyId:
      #  resourceGroup:
      #  The ID of the subscription containing the storage account, if different from the cluster’s subscription. (Azure only)
      #  subscriptionId:
      #  storageAccount:
      #  publicUrl:
      #  Name of the GCP service account to use for this backup storage location. Specify the
      #  service account here if you want to use workload identity instead of providing the key file.(GCP only)
      #  serviceAccount: velero-server
      #  Option to skip certificate validation or not if insecureSkipTLSVerify is set to be true, the client side should set the
      #  flag. For Velero client Command like velero backup describe, velero backup logs needs to add the flag --insecure-skip-tls-verify
      #  insecureSkipTLSVerify:

    # Parameters for the VolumeSnapshotLocation(s). Configure multiple by adding other element(s) to the volumeSnapshotLocation slice.
    # See https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
    volumeSnapshotLocation:
      # name is the name of the volume snapshot location where snapshots are being taken. Required.
    - name: aws-default
      # provider is the name for the volume snapshot provider.
      provider: aws
      credential:
        # name of the secret used by this volumeSnapshotLocation.
        name:
        # name of key that contains the secret data to be used.
        key:
      # Additional provider-specific configuration. See link above
      # for details of required/optional fields for your provider.
      config:
        region: eu-central-1
    #    apiTimeout:
    #    resourceGroup:
    #    The ID of the subscription where volume snapshots should be stored, if different from the cluster’s subscription. If specified, also requires `configuration.volumeSnapshotLocation.config.resourceGroup`to be set. (Azure only)
    #    subscriptionId:
    #    incremental:
    #    snapshotLocation:
    #    project:

  ##
  ## End of backup/snapshot location settings.
  ##


  ##
  ## Settings for additional Velero resources.
  ##
  rbac:
    # Whether to create the Velero role and role binding to give all permissions to the namespace to Velero.
    create: true
    # Whether to create the cluster role binding to give administrator permissions to Velero
    clusterAdministrator: true
    # Name of the ClusterRole.
    clusterAdministratorName: cluster-admin

  # Information about the Kubernetes service account Velero uses.
  serviceAccount:
    server:
      create: true
      name: velero-server
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::934382447941:role/velero
      labels:

  # Info about the secret to be used by the Velero deployment, which
  # should contain credentials for the cloud provider IAM account you've
  # set up for Velero.
  credentials:
    # Whether a secret should be used. Set to false if, for examples:
    # - using kube2iam or kiam to provide AWS IAM credentials instead of providing the key file. (AWS only)
    # - using workload identity instead of providing the key file. (GCP only)
    useSecret: false

  # Whether to create backupstoragelocation crd, if false => do not create a default backup location
  backupsEnabled: true
  # Whether to create volumesnapshotlocation crd, if false => disable snapshot feature
  snapshotsEnabled: true